name: bidbot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  sticky_and_expandable_list: ^1.0.2
  country_code_picker: ^2.0.2
  font_awesome_flutter: ^9.2.0
  validators: ^3.0.0
  table_calendar: ^3.0.3
  file_picker: ^4.2.7
  markdown_editable_textinput: ^2.0.2
  flutter_pdfview: ^1.2.1
  open_file: ^3.2.1
  path_provider: ^2.0.2
  flutter_html: ^2.2.1
  http_parser: ^4.0.0
  html: ^0.15.0
  flutter_markdown: ^0.6.0
  dotted_decoration: ^1.2.2
  flutter_downloader: ^1.3.4
  android_path_provider: any
  device_info: any
  permission_handler: ^8.3.0
  flutter_native_splash: ^1.3.2
  flutter_swipe_action_cell: ^2.1.6
  animations: ^2.0.2
  dots_indicator: ^2.0.0
  uni_links: ^0.5.1
  share: ^2.0.4
  percent_indicator: ^4.0.0
  liquid_progress_indicator: ^0.4.0
#  bloc: any
#  provider: ^6.0.2
  expandable_group: ^0.0.8
#  get:
  settings_ui: ^2.0.2
  flutter_intro: ^2.3.1
#  get_storage: ^2.0.3
  is_first_run: ^1.0.0
  tutorial_coach_mark: ^1.2.2
  local_auth: ^1.1.11
#  ext_storage: ^1.0.3
  dio: ^4.0.4
  data_connection_checker: ^0.3.4

  #  flutter_sticky_header: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/image/
     - asset/image/bidding/
     - asset/image/2.0x/
     - asset/image/3.0x/
     - asset/image/background_image.png
     - asset/image/tristate1.png
     - asset/image/eyes.png
     - asset/image/hands.png
     - asset/image/Group1114.png
     - asset/image/hands-combine.png
     - asset/image/animation/bid-bot-loader-2.gif
     - asset/image/leftback.png
     - asset/image/profile-placeholder.png
     - asset/image/sort_alpha.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: asset/fonts/Poppins/Poppins-Medium.ttf
           weight: 300
         - asset: asset/fonts/Poppins/Poppins-Bold.ttf
           weight: 600
         - asset: asset/fonts/Poppins/Poppins-Italic.ttf
           weight: 500
         - asset: asset/fonts/Poppins/Poppins-Regular.ttf
           weight: 500
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
